### PR TITLE
Per-field multiplicity polymorphism

### LINKED ISSUE #218: Regression in pattern guard exaustiveness checking
Pre-linear types

```
Prelude> :set -fwarn-incomplete-patterns 
Prelude> c :: Int; c | False = 0 | True = 1
```

With linear types:

```
Prelude> :set -fwarn-incomplete-patterns
Prelude> c :: Int; c | False = 0 | True = 1

<interactive>:3:11: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for 'c': Guards do not cover entire pattern space
```

I assume that `True` having a wrapper confuses the guard checker. (probably the wrapper for `False` is irrelevant).

### PR DESCRIPTION
**Pull request by monoidal**
Refs #114.

This also fixes #218. Previously, the guard `True` was not considered to be complete by `isTrueLHsExpr` because of the implicit `Omega`; now, booleans no longer have an implicit multiplicity argument.

### CODE REVIEW

File: compiler/prelude/TysPrim.hs [hunk 1]
```diff
@@ -369,6 +370,8 @@ openBetaTy  = mkTyVarTy openBetaTyVar
 multiplicityTyVar :: TyVar
 multiplicityTyVar = mkTemplateTyVars (repeat multiplicityTy) !! 13
 
+multiplicityTyVarList :: [a] -> [TyVar]
+multiplicityTyVarList l = take (length l) $ drop 13 $ mkTemplateTyVars (repeat multiplicityTy)
```
Comment (aspiwack) [inline compiler/prelude/TysPrim.hs]: Doesn't it make `multiplicityTyVar`, above, dead?

Could it cause name conflicts? (I was wondering the same for `multiplicityTyVar`, I don't know whether it's the right way).

**Comment by monoidal** [comment]
This solves only #218 as a byproduct, the debugger issues are still there.

File: compiler/prelude/TysPrim.hs (hunk 1 above)
Comment (monoidal) [reply compiler/prelude/TysPrim.hs]: `multiplicityTyVar` is still used in `funTyCon`.

I'm not sure whether `multiplicityTyVar` is the right approach, either. However, this PR shouldn't introduce new conflicts.
