### PR TITLE
Make multiplicity parameter to functions nominal

### LINKED ISSUE #195: Fix role of multiplicity parameter of (->)
In bd9685c3c2e001a239b4e546e1bb2b3c65ca1457, I added `representational` as the role of multiplicity parameter to `(->)`. This is incorrect - it should be nominal, however, making this change causes a panic during build. The panic comes from `normaliseFfiType` in `TcForeign`; this function apparently expects all roles to be representational. See `Note [FFI type roles]` and this snippet:

```
         | tc_key `elem` [ioTyConKey, funPtrTyConKey, funTyConKey]
                  -- These *must not* have nominal roles on their parameters!
                  -- See Note [FFI type roles]
```

Additionally, we might want to forbid linear arrows in FFI.

### PR DESCRIPTION
**Pull request by monoidal**
Fixes #195.

This means we are lifting the restriction described in Note [FFI type roles] and can remove it.

### CODE REVIEW

File: libraries/ghc-prim/GHC/Types.hs [hunk 1]
```diff
@@ -205,13 +205,6 @@ or the 'Prelude.>>' and 'Prelude.>>=' operations from the 'Prelude.Monad'
 class.
 -}
 newtype IO a = IO (State# RealWorld -> (# State# RealWorld, a #))
-type role IO representational
```
Comment (aspiwack) [inline libraries/ghc-prim/GHC/Types.hs]: Is it a good idea to remove this? Was the role just to catch some potential role changes which would require changing `TcForeign` (in which case, yeah, remove).

Comment (monoidal) [reply libraries/ghc-prim/GHC/Types.hs]: Yes, I believe the comment below was the only reason for the role declaration.
