### PR TITLE
Fix multiple scaling issues

### LINKED ISSUE #22: Handle pattern synonyms
Pattern-synonyms are not correctly implemented for linearly typed patterns.

That pattern-synonyms are bidirectional may cause additional type-checking challenges.

This has yet to be explored.

### LINKED ISSUE #212: Support for multiplicity-polymorphic datatypes
```
data T a where MkT :: a -->.(p) T a
```
gives an ambiguity error. Currently we multiply all multiplicities in constructors, but we should really put a submultiplicity constraint. Also check `data T p a where MkT :: a -->. (p) T p a`.

### PR DESCRIPTION
**Pull request by monoidal**
This fixes #212, `data T p a where MkT :: a -->.(p) T p a`.

There were two bugs.
1. During kind-checking of a datacon, we didn't call `tcMult` on field multiplicities. As a result, `T` was presumed to be `* -> * -> *` which caused a problem during type-checking.

2. The pattern of using `Compose` with `Traversable` instance for `Scaled` is completely wrong.

A call such as

```mapM zonk (Compose [Scaled m1 t1, Scaled m2 t2])```

is equivalent to

```Compose [Scaled m1 (zonk t1), Scaled m2 (zonk t2)]```

while we need `Scaled (zonk m1) (zonk t1)`.

It turned out that every place using `Compose` was incorrectly ignoring multiplicities.

Instead of `substTys` that is polymorphic in `Traversable t`, we're back to monomorphic `substTys` that takes only a list and a new function `substScaledTys`. I removed unneccessary polymorphism to make the patch smaller, and the `Traversable` instance so that it won't tempt us again.

The test `MultConstructor` is not fully working - the function `g` causes a Lint error. This is a different bug though.

### CODE REVIEW

File: compiler/rename/RnUtils.hs [hunk 1]
```diff
@@ -190,9 +189,10 @@ addFvRn :: FreeVars -> RnM (thing, FreeVars) -> RnM (thing, FreeVars)
 addFvRn fvs1 thing_inside = do { (res, fvs2) <- thing_inside
                                ; return (res, fvs1 `plusFV` fvs2) }
 
-mapFvRn :: (Traversable t ) => (a -> RnM (b, FreeVars)) -> t a -> RnM (t b, FreeVars)
+mapFvRn :: (a -> RnM (b, FreeVars)) -> [a] -> RnM ([b], FreeVars)
 mapFvRn f xs = do stuff <- mapM f xs
-                  return (fmap fst stuff, plusFVs . map snd $ toList stuff)
+                  case unzip stuff of
+                      (ys, fvs_s) -> return (ys, plusFVs fvs_s)
```
Comment (monoidal) [inline compiler/rename/RnUtils.hs]: (this is just a revert to the original version in master)

**Comment by aspiwack** [comment]
> It turned out that every place using `Compose` was incorrectly ignoring multiplicities.

Ah yes. It probably made sense at the time, and I didn't correctly anticipate that types would be there and properly abstract. These date back from the early prototype, before POPL. I have to apologise for this.

File: compiler/rename/RnUtils.hs (hunk 1 above)
Comment (aspiwack) [reply compiler/rename/RnUtils.hs]: Sweet reversals of goodness :slightly_smiling_face:
